apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config
data:
  APP_ENV: "dev"            
  BATCH_SIZE: "500"
  BATCH_WINDOW_MS: "50"
  TRADES_OUT_TOPIC: "trades.out"
  WALLET_TX_TOPIC: "wallet.tx"
  KAFKA_GROUP_ID: "wallet-consumer"
