apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: wallet
  labels:
    app: wallet
    service: wallet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet
  template:
    metadata:
      labels:
        app: wallet
        service: wallet
        env: prod
        owner: wallet
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: wallet
          image: registry.upx.exchange/exchange/wallet:v0.7.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          env:
           - name: QUEUE_BACKEND
            value: "kafka"
           - name: KAFKA_BOOTSTRAP
            value: "kafka.data-platform.svc.cluster.local:9092"
           - name: KAFKA_TOPIC
            value: "wallet-withdraw"
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wallet-secret
                  key: HSM_API_KEY
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallet-secret
                  key: HOT_WALLET_PASSWORD
            - name: KAFKA_SASL_MECHANISMS
              value: "PLAIN"
            - name: KAFKA_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT" 
            - name: PORT
              value: "8081"
            - name: HSM_ENDPOINT
              value: "http://hsm-mock.wallet.svc.cluster.local:9000"
            - name: QUEUE_BACKEND
              value: "redis"
            - name: REDIS_HOST
              value: "redis.wallet.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: wallet-secret
                 key: HOT_WALLET_PASSWORD
            - name: REDIS_QUEUE_KEY
              value: "wallet:withdraw:queue"
            - name: HOT_WALLET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallet-secret
                  key: HOT_WALLET_PASSWORD
            - name: HSM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wallet-secret
                  key: HSM_API_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallet-secret
                  key: DB_PASSWORD
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wallet-secret
                  key: HSM_API_KEY
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallet-secret
                  key: HOT_WALLET_PASSWORD      
          envFrom:
            - configMapRef:
                name: wallet-config
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: registry-credentials
