apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - externalsecret.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml

commonLabels:
  app.kubernetes.io/name: svc-wallet
  app.kubernetes.io/part-of: exchange
